import { Pronoun } from "./Pronoun";
import { Tense } from "./Tense";
import { actuar } from "./irregularities/Actuar";
import { adquirir } from "./irregularities/Adquirir";
import { agradecer } from "./irregularities/Agradecer";
import { almorzar } from "./irregularities/Almorzar";
import { andar } from "./irregularities/Andar";
import { arguir } from "./irregularities/Arguir";
import { atacar } from "./irregularities/Atacar";
import { avergonzar } from "./irregularities/Avergonzar";
import { averiguar } from "./irregularities/Averiguar";
import { caber } from "./irregularities/Caber";
import { caer } from "./irregularities/Caer";
import { coger } from "./irregularities/Coger";
import { conducir } from "./irregularities/Conducir";
import { confiar } from "./irregularities/Confiar";
import { conocer } from "./irregularities/Conocer";
import { construir } from "./irregularities/Construir";
import { contar } from "./irregularities/Contar";
import { cruzar } from "./irregularities/Cruzar";
import { dar } from "./irregularities/Dar";
import { Irregularities } from "./irregularities/Irregularity";
import { regularVerb } from "./irregularities/RegularVerb";

let irregularities = new Map<string, Irregularities>([
    ["beber", regularVerb],
    ["vivir", regularVerb],
    ["amar", regularVerb],
    ["actuar", actuar],
    ["acentuar", actuar],
    ["anticuar", actuar],
    ["atenuar", actuar],
    ["conceptuar", actuar],
    ["consensuar", actuar],
    ["continuar", actuar],
    ["desconceptuar", actuar],
    ["deshabituar", actuar],
    ["desvirtuar", actuar],
    ["devaluar", actuar],
    ["efectuar", actuar],
    ["evaluar", actuar],
    ["exceptuar", actuar],
    ["extenuar", actuar],
    ["fluctuar", actuar],
    ["graduar", actuar],
    ["habituar", actuar],
    ["insinuar", actuar],
    ["interactuar", actuar],
    ["menstruar", actuar],
    ["perpetuar", actuar],
    ["puntuar", actuar],
    ["redituar", actuar],
    ["reevaluar", actuar],
    ["revaluar", actuar],
    ["situar", actuar],
    ["tatuar", actuar],
    ["valuar", actuar],
    ["adquirir", adquirir],
    ["inquirir", adquirir],
    ["agradecer", agradecer],
    ["abastecer", agradecer],
    ["aborrecer", agradecer],
    ["acaecer", agradecer],
    ["acontecer", agradecer],
    ["acrecer", agradecer],
    ["adolecer", agradecer],
    ["adormecer", agradecer],
    ["amanecer", agradecer],
    ["anochecer", agradecer],
    ["aparecer", agradecer],
    ["apetecer", agradecer],
    ["atardecer", agradecer],
    ["autoabastecerse", agradecer],
    ["blanquecer", agradecer],
    ["carecer", agradecer],
    ["compadecer", agradecer],
    ["comparecer", agradecer],
    ["conocer", agradecer],
    ["convalecer", agradecer],
    ["crecer", agradecer],
    ["decrecer", agradecer],
    ["desabastecer", agradecer],
    ["desagradecer", agradecer],
    ["desaparecer", agradecer],
    ["desconocer", agradecer],
    ["desentumecer", agradecer],
    ["desfallecer", agradecer],
    ["desfavorecer", agradecer],
    ["desguarnecer", agradecer],
    ["desmerecer", agradecer],
    ["desobedecer", agradecer],
    ["desvanecer", agradecer],
    ["embastecer", agradecer],
    ["embebecer", agradecer],
    ["embellecer", agradecer],
    ["embravecer", agradecer],
    ["embrutecer", agradecer],
    ["empalidecer", agradecer],
    ["empequeñecer", agradecer],
    ["emplastecer", agradecer],
    ["empobrecer", agradecer],
    ["enaltecer", agradecer],
    ["enardecer", agradecer],
    ["encallecer", agradecer],
    ["encanecer", agradecer],
    ["encarecer", agradecer],
    ["enceguecer", agradecer],
    ["endurecer", agradecer],
    ["enflaquecer", agradecer],
    ["enfurecer", agradecer],
    ["engrandecer", agradecer],
    ["enloquecer", agradecer],
    ["enmohecer", agradecer],
    ["enmudecer", agradecer],
    ["ennegrecer", agradecer],
    ["ennoblecer", agradecer],
    ["enorgullecer", agradecer],
    ["enrarecer", agradecer],
    ["enriquecer", agradecer],
    ["enrojecer", agradecer],
    ["enronquecer", agradecer],
    ["ensoberbecer", agradecer],
    ["ensombrecer", agradecer],
    ["ensordecer", agradecer],
    ["entallecer", agradecer],
    ["enternecer", agradecer],
    ["entontecer", agradecer],
    ["entorpecer", agradecer],
    ["entristecer", agradecer],
    ["entumecer", agradecer],
    ["envanecer", agradecer],
    ["envejecer", agradecer],
    ["envilecer", agradecer],
    ["escarnecer", agradecer],
    ["esclarecer", agradecer],
    ["establecer", agradecer],
    ["estremecer", agradecer],
    ["fallecer", agradecer],
    ["favorecer", agradecer],
    ["fenecer", agradecer],
    ["florecer", agradecer],
    ["fortalecer", agradecer],
    ["fosforecer", agradecer],
    ["fosforescer", agradecer],
    ["guarecer", agradecer],
    ["guarnecer", agradecer],
    ["humedecer", agradecer],
    ["incomparecer", agradecer],
    ["languidecer", agradecer],
    ["merecer", agradecer],
    ["nacer", agradecer],
    ["obedecer", agradecer],
    ["obscurecer", agradecer],
    ["ofrecer", agradecer],
    ["oscurecer", agradecer],
    ["pacer", agradecer],
    ["padecer", agradecer],
    ["palidecer", agradecer],
    ["parecer", agradecer],
    ["perecer", agradecer],
    ["permanecer", agradecer],
    ["pertenecer", agradecer],
    ["prevalecer", agradecer],
    ["reaparecer", agradecer],
    ["reblandecer", agradecer],
    ["reconocer", agradecer],
    ["recrudecer", agradecer],
    ["rejuvenecer", agradecer],
    ["renacer", agradecer],
    ["resplandecer", agradecer],
    ["restablecer", agradecer],
    ["reverdecer", agradecer],
    ["robustecer", agradecer],
    ["verdecer", agradecer],
    ["almorzar", almorzar],
    ["disforzar", almorzar],
    ["esforzar", almorzar],
    ["reforzar", almorzar],
    ["andar", andar],
    ["desandar", andar],
]);

export const verbs: string[] = Array.from(irregularities.keys())

export function conjugateIrregular(verb: string, tense: Tense, pronoun: Pronoun): string | undefined {
    return irregularities.get(verb)?.forms(verb)?.get(tense)?.get(pronoun)
}
